### ISSUE TITLE
centos7 安装报错，fibos --version fibos: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by woshidama323** [FIBOSIO/fibos.js#14]
curl -s https://fibos.io/download/installer.sh |sh

fibos --version
fibos: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

env：
version  centos7

**Comment by luoyhang003** [comment]
Centos7 has not been suppoerted yet. We will solve this problem soon.
