### ISSUE TITLE
安装报错 ubuntu-18.04

### ISSUE THREAD

**Issue by R4mble** [FIBOSIO/fibos.js#36]
ubuntu-18.04

fibos: error while loading shared libraries: libicuuc.so.55: cannot open shared object file: No such file or directory

**Comment by luoyhang003** [comment]
You could solve it by exec:

```shell
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7_amd64.deb && sudo dpkg -i libicu55_55.1-7_amd64.deb
```

Besides, you should open an issue at https://github.com/FIBOSIO/fibos , not here.
